### ISSUE TITLE
iteration 2a: as a user, when I click on a movie, the user should be able to see that movie's details only (none of the other movies will be visible): it should just be that movie's details: (header/footer/etc can still be visible, of course!)

### ISSUE THREAD

**Issue by em2396** [em2396/rancid-tomatillos#2]

**Comment by amysiu1028** [comment]
Scenario: The user clicks on a specific movie of interest.

Given: The user has a stable internet connection and the page has loaded.
When: The user clicks on a specific movie.
Then: That specific movie and its details should be displayed on the screen when clicked on.
